### ISSUE TITLE
Menu style "talk_choice" not being respected in some cases.

### ISSUE THREAD

**Issue by GitGodScrub** [multimokia/MAS-Submod-consistent-menus#2]
I am trying out the "talk_choice" menu style. It works just fine in most cases, but sometimes it reverts to the mas_gen_scrollable_menu style.

Example:
The "monika_vehicle" event ( Talk > Hey Monika... > Monika... > What's your favorite car? )
![DDLC_CHXHufaCOD](https://user-images.githubusercontent.com/18603041/88112753-c51e4780-cbb0-11ea-90d3-0f75fdf18f02.png)
(Clicked Yes)

It worked fine in the choice above, but in this one, it bugs out, and appears in the mas_gen_scrollable_menu style.
![DDLC_yboYJOTTF1](https://user-images.githubusercontent.com/18603041/88112625-9011f500-cbb0-11ea-8f1b-36b607c10930.png)

**Comment by GitGodScrub** [comment]
I just checked out the code for monika_vehicle. The last choice is made in a different way than usual, might be the cause of the bug.
![Code_vg5svcRYbf](https://user-images.githubusercontent.com/18603041/88114109-745c1e00-cbb3-11ea-9625-5f32407199fd.png)

**Comment by GitGodScrub** [comment]
![Code_vg5svcRYbf](https://user-images.githubusercontent.com/18603041/88114067-627a7b00-cbb3-11ea-8ac7-4a0aa6d3fb7e.png)

**Comment by multimokia** [comment]
Yeah this case is special, cases where the code explicitly uses a `mas_gen_scrollable` menu cannot be changed. The reason it's done this way is because the normal menu isn't big enough to handle it. So the talk choice menu and even unobstructed choice menus would both have the same issue.

I'm considering this not a bug as a result.
